### ISSUE TITLE
Deleting sugggestions

### ISSUE THREAD

**Issue by okthatsactuallyme** [OtterDevelopment/Astro#8] opened 2022-05-21 08:40 UTC
Sometimes a member misuses the suggestion channel 
Once someone used the suggestion channel to tell us that a bot was down and he couldn't get the roles he wished to 
Can we make it so if it happens, with a command we can delete the suggestion with a command and it won't count the next suggestion as if it came after the deleted suggestion?

Like the deleted suggestion being number 100
and the next suggestion be 100 again rather than 101

**Comment by xPolar** [comment] 2022-05-21 08:41
This is a duplicate of #7, I'll be closing this.

**Closed as not planned by xPolar** 2022-05-21 08:41 UTC
Labels: Enhancement
